# **Feature Scaling**

- Used to make sure that all data on same scale which leads to faster convergance speed
- Here we can see the effect before and after scaling
![alt text](Images\Optimization_zigzag.jpg)


# Data Generation as we won't use actuall dataset for elaboration

In [9]:
import numpy as np
import pandas as pd

np.random.seed(0)

df = pd.DataFrame({
    "small_feature": np.random.rand(100),        # 0–1
    "medium_feature": np.random.rand(100) * 100, # 0–100
    "large_feature": np.random.rand(100) * 10000 # 0–10000
})

print(df.head())
X = df.values.astype(float)



   small_feature  medium_feature  large_feature
0       0.548814       67.781654    3117.958820
1       0.715189       27.000797    6963.434888
2       0.602763       73.519402    3777.518393
3       0.544883       96.218855    1796.036776
4       0.423655       24.875314     246.787284


We will make the following three methods for scaling [Min-Max Scaling , Mean Normalization (strandardization) , Robust Scaling]


# 1. Manual Implementation

**Min-Max**

In [11]:
X_min = X.min(axis=0)
X_max = X.max(axis=0)
Min_Max_Scaled_X = (X - X_min) / (X_max - X_min)
print(Min_Max_Scaled_X[:5])

[[0.55314628 0.67478496 0.30555561]
 [0.72228273 0.2616607  0.6991149 ]
 [0.60799131 0.73291035 0.37305721]
 [0.54915075 0.9628637  0.17026554]
 [0.42591089 0.24012882 0.01171001]]


**Mean Normalization**

In [13]:
X_Mean = X.mean(axis=0)
X_Std = X.std(axis=0)
Standard_Scaled_X = (X - X_Mean) / X_Std
print(Standard_Scaled_X[:5])

[[ 0.26368103  0.54112729 -0.65577964]
 [ 0.84077065 -0.93265417  0.61890425]
 [ 0.45081101  0.74848408 -0.43715133]
 [ 0.25004836  1.56882076 -1.09396537]
 [-0.17044317 -1.00946711 -1.60750475]]


**Robust Scaling**

In [14]:
X_Q1 = np.percentile(X, 25, axis=0)
X_Q3 = np.percentile(X, 75, axis=0)
X_Median = np.median(X, axis=0)
IQR = X_Q3 - X_Q1
Robust_Scaled_X = (X - X_Median) / IQR
print(Robust_Scaled_X[:5])

[[ 0.16990996  0.23611656 -0.35021643]
 [ 0.51748209 -0.70261241  0.34917797]
 [ 0.28261545  0.36819301 -0.2302593 ]
 [ 0.16169921  0.8907086  -0.59064047]
 [-0.09155632 -0.75153861 -0.8724096 ]]


# 2.Using scikit-learn

In [15]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

**Min-Max**

In [16]:
x_min_max_scaled = MinMaxScaler().fit_transform(X)
print(x_min_max_scaled[:5])


[[0.55314628 0.67478496 0.30555561]
 [0.72228273 0.2616607  0.6991149 ]
 [0.60799131 0.73291035 0.37305721]
 [0.54915075 0.9628637  0.17026554]
 [0.42591089 0.24012882 0.01171001]]


**Mean Normalization**

In [17]:
x_standard_scaled = StandardScaler().fit_transform(X)
print(x_standard_scaled[:5])

[[ 0.26368103  0.54112729 -0.65577964]
 [ 0.84077065 -0.93265417  0.61890425]
 [ 0.45081101  0.74848408 -0.43715133]
 [ 0.25004836  1.56882076 -1.09396537]
 [-0.17044317 -1.00946711 -1.60750475]]


**Robust Scaling**

In [18]:
x_robust_scaled = RobustScaler().fit_transform(X)
print(x_robust_scaled[:5])

[[ 0.16990996  0.23611656 -0.35021643]
 [ 0.51748209 -0.70261241  0.34917797]
 [ 0.28261545  0.36819301 -0.2302593 ]
 [ 0.16169921  0.8907086  -0.59064047]
 [-0.09155632 -0.75153861 -0.8724096 ]]


# 3.Pytorch 

In [20]:
import torch
X_torch = torch.tensor(X, dtype=torch.float32)

**Min-Max**

In [21]:
min_values, _ = torch.min(X_torch, dim=0)
max_values, _ = torch.max(X_torch, dim=0)
min_max_scaled_torch = (X_torch - min_values) / (max_values - min_values)
print(min_max_scaled_torch[:5])

tensor([[0.5531, 0.6748, 0.3056],
        [0.7223, 0.2617, 0.6991],
        [0.6080, 0.7329, 0.3731],
        [0.5492, 0.9629, 0.1703],
        [0.4259, 0.2401, 0.0117]])


**Mean Normalization**

In [22]:
mean_values = torch.mean(X_torch, dim=0)
std_values = torch.std(X_torch, dim=0)
standard_scaled_torch = (X_torch - mean_values) / std_values
print(standard_scaled_torch[:5])

tensor([[ 0.2624,  0.5384, -0.6525],
        [ 0.8366, -0.9280,  0.6158],
        [ 0.4486,  0.7447, -0.4350],
        [ 0.2488,  1.5610, -1.0885],
        [-0.1696, -1.0044, -1.5994]])


**Robust Scaling**

In [23]:
q1_values = torch.quantile(X_torch, 0.25, dim=0)
q3_values = torch.quantile(X_torch, 0.75, dim=0)
median_values = torch.median(X_torch, dim=0).values
iqr_values = q3_values - q1_values
robust_scaled_torch = (X_torch - median_values) / iqr_values

# 4. TensorFlow

In [24]:
import tensorflow as tf
X_tf = tf.constant(X, dtype=tf.float32)

**Min-Max**


In [25]:
min_values_tf = tf.reduce_min(X_tf, axis=0)
max_values_tf = tf.reduce_max(X_tf, axis=0)
min_max_scaled_tf = (X_tf - min_values_tf) / (max_values_tf - min_values_tf)
print(min_max_scaled_tf[:5])

tf.Tensor(
[[0.5531463  0.674785   0.30555558]
 [0.7222827  0.26166072 0.69911486]
 [0.6079913  0.7329104  0.3730572 ]
 [0.54915076 0.96286374 0.17026554]
 [0.4259109  0.24012884 0.01171   ]], shape=(5, 3), dtype=float32)


**Mean Normalization**


In [26]:
mean_values_tf = tf.reduce_mean(X_tf, axis=0)
std_values_tf = tf.math.reduce_std(X_tf, axis=0)
standard_scaled_tf = (X_tf - mean_values_tf) / std_values_tf
print(standard_scaled_tf[:5])

tf.Tensor(
[[ 0.26368096  0.5411272  -0.65577936]
 [ 0.8407705  -0.93265426  0.61890465]
 [ 0.45081082  0.74848396 -0.437151  ]
 [ 0.25004828  1.5688207  -1.093965  ]
 [-0.17044333 -1.0094671  -1.6075045 ]], shape=(5, 3), dtype=float32)


**Robust Scaling**


In [ ]:
import tensorflow_probability as tfp

q1_values_tf = tfp.stats.percentile(X_tf, 25.0, axis=0)
q3_values_tf = tfp.stats.percentile(X_tf, 75.0, axis=0)
median_values_tf = tfp.stats.percentile(X_tf, 50.0, axis=0)
iqr_values_tf = q3_values_tf - q1_values_tf
robust_scaled_tf = (X_tf - median_values_tf) / iqr_values_tf
print(robust_scaled_tf[:5])